### ISSUE TITLE
Error: Cloudinit metadata service not found.

### ISSUE THREAD

**Issue by srkaviani** [linitio/openstack-alpine-image#1]
Hello 
Thanks for this useful repo.
I Have a Problem, I Launched a instance with cloudinit userdata but in VNC I See "metadata service not found." and cloudinit is not running correctly.
The instance has get IP Address but Doesn't get user data or SSH Keys.
(This problem is only for alpine cloud images and other images (ubuntu , centos , ....) are working properly with our Cloudinit )

**Comment by kallioli** [comment]
Hello, thanks for interest of this project :)

Could you send a screen of VNC result please, i have test another time the latest version of the image on several openstack clusters and it's working.

Normally even if the instance can't reach the metadata server you can use configdrive (not the best solution but can help for debug).

Could you send more informations, about this problem so that I can help you ?

Have a nice day

**Comment by srkaviani** [comment]
I also tested config drive option (and img_config_drive=mandatory in image metadata's ) and problem not solved.
Screenshot of my instance VNC attached.

![Screenshot (76)](https://user-images.githubusercontent.com/90821955/184531180-40eeb3de-176b-4e61-a7b8-c3a8c2ca0443.png)

**Comment by kallioli** [comment]
What kind of metadata service you use on your infrastructure ? I think you are using a datasource not added in cloud.cfg file. 

https://cloudinit.readthedocs.io/en/latest/topics/datasources.html

Actually in the image we have enable theses datasources:

OpenStack, NoCloud, AltCloud, ConfigDrive, OVF, None

Could you check you areusing one of theses one.

Have a nice day

**Comment by srkaviani** [comment]
I made some changes in  cloud.cfg file of project.
How can i build qcow2 image ?

**Comment by kallioli** [comment]
The CI process will build a new image automatically if you follow this process :

- Fork the project
- Clone it locally
- Create a new branch 
- Add your changes 
- Push it to your repository
- Create a merge request on GitHub
